import PITCHES_BY_NOTE_NAMES from './pitchesByNoteNames.js'

export default {
  'c major|a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 } ],

  'g major|e minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 } ],
  'd major|b minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 } ],
  'a major|f sharp minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: +1 } ],
  'e major|c sharp minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: +1 } ],
  'b major|g sharp minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: +1 } ],
  'f sharp major|d sharp minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: +1 } ],
  'c sharp major|a sharp minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: +1 } ],

  'f major|d minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 } ],
  'b flat major|g minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 } ],
  'e flat major|c minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: -1 } ],
  'a flat major|f minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: -1 } ],
  'd flat major|b flat minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: -1 } ],
  'g flat major|e flat minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: -1 } ],
  'c flat major|a flat minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: -1 }, { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: -1 } ],

  'g major to c major|g major to a minor|e minor to c major|e minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 } ],
  'd major to c major|d major to a minor|b minor to c major|b minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 } ],
  'a major to c major|a major to a minor|f sharp minor to c major|f sharp minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 } ],
  'e major to c major|e major to a minor|c sharp minor to c major|c sharp minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 } ],
  'b major to c major|b major to a minor|g sharp minor to c major|g sharp minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 } ],
  'f sharp major to c major|f sharp major to a minor|d sharp minor to c major|d sharp minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 } ],
  'c sharp major to c major|c sharp major to a minor|a sharp minor to c major|a sharp minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: +1 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 } ],

  'f major to c major|f major to a minor|d minor to c major|d minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 } ],
  'b flat major to c major|b flat major to a minor|g minor to c major|g minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 } ],
  'e flat major to c major|e flat major to a minor|c minor to c major|c minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 } ],
  'a flat major to c major|a flat major to a minor|f minor to c major|f minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 } ],
  'd flat major to c major|d flat major to a minor|b flat minor to c major|b flat minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 } ],
  'g flat major to c major|g flat major to a minor|e flat minor to c major|e flat minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 } ],
  'c flat major to c major|c flat major to a minor|a flat minor to c major|a flat minor to a minor': [ { pitch: PITCHES_BY_NOTE_NAMES['f'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['c'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['g'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['d'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['a'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['e'], midiPitchAdjustment: 0 }, { pitch: PITCHES_BY_NOTE_NAMES['b'], midiPitchAdjustment: 0 } ]
}
